project:
  type: website
  output-dir: docs

website:
  title: "mehran92.github.io"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/mehranvt/mehran92.github.io
     
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

